minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - get-shit-done-cc@1.34.2

trustPolicy: no-downgrade
trustPolicyIgnoreAfter: 14400 # 10 days

blockExoticSubdeps: true
onlyBuiltDependencies:
  - esbuild
  - protobufjs
